version: "3"

services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: smart-light-frontend
    hostname: smart-light-frontend
    volumes:
      - ./dist:/var/www/web
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    ports:
      - "80:80"
    restart: always

  npm-build:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: npm-build
    volumes:
      - ./:/app
